export interface AssetInterface {
  uuid: string;
  id?: number;
  type_id: number;
  status_type_id: number;
  name: string;
  address_name?: string;
  address_uuid?: string;
  address_id?: number;
  work_order_uuid?: string;
  delete_action_uuid?: string;
  system_type?: string;
  manufacturer?: string;
  model_number?: string;
  model_not_readable?: number;
  serial_number?: string;
  serial_number_not_readable?: number;
  source?: string;
  identifier?: string;
  heat_type?: string;
  voltage_type?: string;
  refrigerant_type?: string;
  other_refrigerant_type?: string;
  fresh_air?: string;
  filter_quantity?: string;
  filter_size?: string;
  belt?: number;
  belt_size?: string;
  unit_condition?: string;
  recommendations?: string;
  coords_accuracy?: string;
  location?: string;
  latitude?: string;
  longitude?: string;
  area_served_type_id?: number;
  thermostat_make?: string;
  thermostat_model?: string;
  tonnage?: string;
  level_type_id?: number;
  level_comment?: string;
  exterior_side_type_id?: number;
  exterior_side_comment?: string;
  room_type_id?: number;
  room_comment?: string;
  unit_number?: number;
  dimension?: string;
  replacement_type_id?: number;
  material_type_id?: number;
  material_color_type_id?: number;
  grid_pattern_type_id?: number;
  condition_type_id?: number;
  floor_type_id?: number;
  floor_comment?: string;
  wall_material_type_id?: number;
  existing_bath_wall_material_type_id?: number;
  removal_of_material_type_id?: number;
  condo_conditions_type_id?: number;
  dimension_bath_door?: string;
  dimension_bath_hallway?: string;
  bath_door_type_id?: number;
  bath_conditions_type_id?: number;
  comment?: string;
  hash?: string;
  sync?: number;
  created_at?: string;
  updated_at?: string;

  //extra fields
  total_photos?: number;
  dimension_bath_door_height?: number | string;
  dimension_bath_door_width?: number | string;
  dimension_bath_hallway_width?: number | string;
  dimension_depth?: number | string;
  dimension_height?: number | string;
  dimension_width?: number | string;
}
