DELETE FROM migrations;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS works;
DROP TABLE IF EXISTS work_rooms;
DROP TABLE IF EXISTS work_room_repairs;

