CREATE TABLE `bill_entries`
(
    `uuid`                         TEXT NOT NULL,
    `id`                           INTEGER,
    `bill_id`                      INTEGER,
    `bill_status_type_id`          INTEGER,
    `type_id`                      INTEGER,
    `previous_bill_status_type_id` INTEGER,
    `supplier_person_id`           INTEGER,
    `supplier_name`                TEXT,
    `approval_person_id`           INTEGER,
    `link_person_wo_id`            INTEGER,
    `object_type`                  TEXT,
    `object_uuid`                  TEXT,
    `step_name`                    TEXT,
    `unit_down`                    INTEGER,
    `desc`                         TEXT,
    `subcontractor_name`           TEXT,
    `subcontractor_phone`          TEXT,
    `qty`                          NUMBER,
    `unit`                         TEXT    DEFAULT 'pcs',
    `men`                          INTEGER,
    `hrs`                          NUMBER,
    `price`                        NUMBER,
    `total`                        NUMBER,
    `item_code`                    TEXT,
    `item_id`                      INTEGER,
    `item_lead_time_type_id`       INTEGER,
    `labor_rate_type_id`           INTEGER,
    `trade_type_id`                INTEGER,
    `incorrect_type_id`            INTEGER,
    `from_inventory`               INTEGER DEFAULT 0,
    `tax_amount`                   NUMBER,
    `transaction_number`           TEXT,
    `reimbursement`                INTEGER,
    `comment`                      TEXT,
    `hash`                         TEXT,
    `sync`                         INTEGER DEFAULT 0,
    `ready_at`                     TEXT    DEFAULT NULL,
    `created_at`                   TEXT,
    `updated_at`                   TEXT,
    PRIMARY KEY (uuid)
)
